print("I will prepare food")
print("I have give", 34 + 42/2, "to Karan")
print("What is 3 + 2?", 3 + 2)
print("What is greater?",5 > -2)
print("Is it greater?", 5 > -2)
print("Is it greater or equal?", 5 >= -2)
